#!/bin/bash
#
# define_requirements.sh
#
# This script takes a high-level strategy plan and uses the LLM to expand it
# into a set of clear, specific, and testable requirements. It serves as the
# bridge between the strategic phase and the detailed task planning phase.
#
# The output is a markdown-formatted file containing the detailed requirements.
#
# Usage: ./define_requirements.sh
#
# Prerequisites:
#   - A strategy plan file must exist at the path specified by $STRATEGY_PLAN_FILE.
#     This is typically generated by 'strategize_project.sh'.
#

set -euo pipefail
IFS=$'\n\t'

# Source utility functions and environment variables
source "$(dirname "${BASH_SOURCE[0]}")/utils.sh"
setup_env

log_info "Checking for input strategy plan at: $STRATEGY_PLAN_FILE"
# The '-s' flag checks if the file exists and is not empty.
if [[ ! -s "$STRATEGY_PLAN_FILE" ]]; then
    log_error "Strategy plan file is missing or empty. Please run 'strategize_project.sh' first to generate it."
fi

log_info "Generating requirements from strategies..."

# 1. Read the strategy plan file using `cat`.
# 2. Pipe the content to the `send_prompt.sh` script.
# 3. Use the `--prompt` argument to instruct the LLM to convert the plan into requirements.
# 4. Redirect the final output from the LLM to the requirements file.
cat "$STRATEGY_PLAN_FILE" | "$PRISM_QUANTA_ROOT/scripts/send_prompt.sh" --prompt "From the following plan, define a list of clear, specific, and testable requirements in markdown format:" > "$REQUIREMENTS_FILE"

log_info "Requirements written to $REQUIREMENTS_FILE."
